### PR TITLE
Fix `--local` and default true for clean

### LINKED ISSUE #72: [BUG]
**Describe the bug**
Network performance tests run locally does not schedule client and server pods on same node

**To Reproduce**
1. Run a NPT  by issuing the following command with the local flag **bin/amd64/k8s-netperf --local**
2. Verify using this command to see if client_pod and server pod are scheduled on same node. **oc get po  -owide -n netperf**

**Expected behavior**
client_pod and server pod must be scheduled on same node per instruction

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

### PR DESCRIPTION
**Pull request by jtaleric**
### Description
Running with `--local` was borken due to missing affinity rules.

Leaving pods around makes testing quick, however can cause scheduling issues when introducing new tests. To avoid scheduling issues, we will have have the SUT be cleaned up after execution (or before).

### Fixes
Fixes #72

### CODE REVIEW

File: pkg/k8s/kubernetes.go [hunk 1]
```diff
@@ -153,30 +185,61 @@ func BuildSUT(client *kubernetes.Clientset, s *config.PerfScenarios) error {
...
-			},
-		},
-	}
 	if z != "" {
 		if numNodes > 1 {
 			cdpAcross.NodeAffinity = apiv1.NodeAffinity{
 				PreferredDuringSchedulingIgnoredDuringExecution: zoneNodeSelectorExpression,
 				RequiredDuringSchedulingIgnoredDuringExecution:  workerNodeSelectorExpression,
 			}
+			cdpAcross.PodAntiAffinity = apiv1.PodAntiAffinity{
```
Comment (vishnuchalla) [inline pkg/k8s/kubernetes.go:194]: Looks like we have this pod antiaffinity term in both `if` and `else` clause. Can we move it outside of it if is obvious to happen irrespective of those conditions?

File: pkg/k8s/kubernetes.go [hunk 2]
```diff
@@ -207,6 +270,20 @@ func BuildSUT(client *kubernetes.Clientset, s *config.PerfScenarios) error {
 		Command:   []string{"/bin/bash", "-c", fmt.Sprintf("netserver && iperf3 -s -p %d && sleep 10000000", IperfServerCtlPort)},
 		Port:      NetperfServerCtlPort,
 	}
+	if s.NodeLocal {
+		sdp.PodAffinity = apiv1.PodAffinity{
+			RequiredDuringSchedulingIgnoredDuringExecution: []apiv1.PodAffinityTerm{
```
Comment (vishnuchalla) [inline pkg/k8s/kubernetes.go:275]: Can we store this rule in some var/separate function and re-use it, as it seems to be appearing at many other places.

**Review by vishnuchalla — CHANGES_REQUESTED** [review]

File: pkg/k8s/kubernetes.go [hunk 3]
```diff
@@ -317,6 +388,55 @@ func WaitForReady(c *kubernetes.Clientset, dp DeploymentParams) (bool, error) {
...
+	if err != nil {
+		return false, err
+	}
+	defer dw.Stop()
+	for event := range dw.ResultChan() {
+		if event.Type == watch.Deleted {
+			return true, nil
+		}
+	}
+	return false, fmt.Errorf("❌ Deployment delete issues")
```
Comment (vishnuchalla) [inline pkg/k8s/kubernetes.go:404]: Correct me if I am wrong, I don't think this statement is reachable. Because, `dw.ResultChan()` keeps on listening for the events indefinitely until the deployment is deleted. Instead we can consider a `timeout` to indicate the deployment deletion failure. But open to other thoughts too.

File: pkg/k8s/kubernetes.go [hunk 4]
```diff
@@ -317,6 +388,55 @@ func WaitForReady(c *kubernetes.Clientset, dp DeploymentParams) (bool, error) {
...
+}
+
+// GetZones will determine if we have a multiAZ/Zone cloud.
+func GetZones(c *kubernetes.Clientset) (string, int, error) {
```
[the remark this answers is not in the document]
Comment (jtaleric) [reply pkg/k8s/kubernetes.go:380]: Good catch, I am not even using `GetZones`

File: pkg/k8s/kubernetes.go (hunk 3 above)
Comment (jtaleric) [reply pkg/k8s/kubernetes.go:376]: ` If an error occurs or Stop() is called, the implementation will close this channel and release any resources used by the watch` 

so, I will add a `TimeoutSeconds` to the `ListOptions`

**Review by vishnuchalla — APPROVED** [review]
Looks good to me. Thank you!
